package com.aurelia.world;

/**
 * GENERATED by gen_lairs.py. Each lair template's size, floor height, Lair Seal and beacon, as
 * {width, height, length, floor, sealX, sealY, sealZ, beaconX, beaconY, beaconZ} in template space.
 */
public final class LairLayout {
    private LairLayout() {}

    public static int[] get(String id) {
        return switch (id) {
            case "thornmaw" -> new int[] {81, 100, 81, 14, 40, 14, 32, 40, 14, 38};
            case "hollowbark" -> new int[] {81, 100, 81, 14, 40, 20, 18, 40, 20, 14};
            case "rot_matron" -> new int[] {81, 80, 81, 22, 40, 6, 40, 40, 6, 46};
            case "galeclaw" -> new int[] {81, 110, 81, 30, 40, 80, 40, 40, 80, 47};
            case "thunder_colossus" -> new int[] {81, 90, 81, 30, 40, 30, 40, 40, 30, 46};
            case "squall_seraph" -> new int[] {81, 100, 81, 30, 40, 36, 18, 40, 36, 14};
            case "cinderjaw" -> new int[] {81, 80, 81, 22, 40, 6, 40, 40, 6, 46};
            case "chainwarden" -> new int[] {81, 90, 81, 3, 40, 3, 40, 40, 3, 46};
            case "ashen_choir" -> new int[] {81, 100, 81, 3, 40, 9, 18, 40, 9, 14};
            case "reef_crusher" -> new int[] {81, 90, 81, 26, 40, 26, 40, 40, 26, 46};
            case "drowned_admiral" -> new int[] {81, 100, 81, 26, 40, 26, 32, 40, 26, 38};
            case "abyssal_siren" -> new int[] {81, 100, 81, 26, 40, 32, 18, 40, 32, 14};
            case "frostmaw" -> new int[] {81, 80, 81, 22, 40, 6, 40, 40, 6, 46};
            case "rime_knight" -> new int[] {81, 90, 81, 14, 40, 14, 40, 40, 14, 46};
            case "the_mourner" -> new int[] {81, 100, 81, 14, 40, 20, 18, 40, 20, 14};
            case "dune_tyrant" -> new int[] {81, 100, 81, 14, 40, 14, 32, 40, 14, 38};
            case "sand_pharaoh" -> new int[] {81, 100, 81, 14, 40, 20, 18, 40, 20, 14};
            case "glass_djinn" -> new int[] {81, 110, 81, 14, 40, 64, 40, 40, 64, 47};
            case "pendulum_butcher" -> new int[] {81, 90, 81, 30, 40, 30, 40, 40, 30, 46};
            case "gearwyrm" -> new int[] {81, 80, 81, 30, 40, 14, 40, 40, 14, 46};
            case "hourless_oracle" -> new int[] {81, 110, 81, 30, 40, 80, 40, 40, 80, 47};
            case "rot_behemoth" -> new int[] {81, 80, 81, 22, 40, 6, 40, 40, 6, 46};
            case "pale_gardener" -> new int[] {81, 100, 81, 3, 40, 9, 18, 40, 9, 14};
            case "lumen_horror" -> new int[] {81, 110, 81, 3, 40, 53, 40, 40, 53, 47};
            case "herald_of_ruin" -> new int[] {81, 90, 81, 30, 40, 30, 40, 40, 30, 46};
            case "herald_of_silence" -> new int[] {81, 110, 81, 30, 40, 80, 40, 40, 80, 47};
            default -> null;
        };
    }
}
