package com.aurelia.registry;

import com.aurelia.AureliaMod;
import com.aurelia.item.BestiaryItem;
import com.aurelia.item.WayfinderItem;
import java.util.List;
import net.minecraft.world.entity.decoration.PaintingVariant;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/** GENERATED by gen_extras.py. The extras: realm masonry, the Wayfinder's Lodestar, the Aurelian Bestiary and the paintings. */
public final class ExtraContent {
    private ExtraContent() {}

    public static final DeferredRegister<PaintingVariant> PAINTINGS = DeferredRegister.create(ForgeRegistries.PAINTING_VARIANTS, AureliaMod.MODID);

    public static final RegistryObject<Item> WAYFINDERS_LODESTAR = ModItems.ITEMS.register("wayfinders_lodestar",
            () -> new WayfinderItem(new Item.Properties().stacksTo(1).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> AURELIAN_BESTIARY = ModItems.ITEMS.register("aurelian_bestiary",
            () -> new BestiaryItem(new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON)));

    public static final RegistryObject<Block> GROVE_BRICKS = ModBlocks.BLOCKS.register("grove_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> GROVE_BRICKS_ITEM = ModItems.ITEMS.register("grove_bricks", () -> new BlockItem(GROVE_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> GROVE_BRICK_STAIRS = ModBlocks.BLOCKS.register("grove_brick_stairs", () -> new StairBlock(() -> GROVE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> GROVE_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("grove_brick_stairs", () -> new BlockItem(GROVE_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> GROVE_BRICK_SLAB = ModBlocks.BLOCKS.register("grove_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> GROVE_BRICK_SLAB_ITEM = ModItems.ITEMS.register("grove_brick_slab", () -> new BlockItem(GROVE_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> GROVE_SIGIL_STONE = ModBlocks.BLOCKS.register("grove_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> GROVE_SIGIL_STONE_ITEM = ModItems.ITEMS.register("grove_sigil_stone", () -> new BlockItem(GROVE_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> GROVE_SIGIL_LAMP = ModBlocks.BLOCKS.register("grove_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> GROVE_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("grove_sigil_lamp", () -> new BlockItem(GROVE_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> SKYREACH_BRICKS = ModBlocks.BLOCKS.register("skyreach_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.QUARTZ).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SKYREACH_BRICKS_ITEM = ModItems.ITEMS.register("skyreach_bricks", () -> new BlockItem(SKYREACH_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> SKYREACH_BRICK_STAIRS = ModBlocks.BLOCKS.register("skyreach_brick_stairs", () -> new StairBlock(() -> SKYREACH_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.QUARTZ).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SKYREACH_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("skyreach_brick_stairs", () -> new BlockItem(SKYREACH_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> SKYREACH_BRICK_SLAB = ModBlocks.BLOCKS.register("skyreach_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.QUARTZ).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SKYREACH_BRICK_SLAB_ITEM = ModItems.ITEMS.register("skyreach_brick_slab", () -> new BlockItem(SKYREACH_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> SKYREACH_SIGIL_STONE = ModBlocks.BLOCKS.register("skyreach_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.QUARTZ).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SKYREACH_SIGIL_STONE_ITEM = ModItems.ITEMS.register("skyreach_sigil_stone", () -> new BlockItem(SKYREACH_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> SKYREACH_SIGIL_LAMP = ModBlocks.BLOCKS.register("skyreach_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.QUARTZ).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> SKYREACH_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("skyreach_sigil_lamp", () -> new BlockItem(SKYREACH_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> HOLLOW_BRICKS = ModBlocks.BLOCKS.register("hollow_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> HOLLOW_BRICKS_ITEM = ModItems.ITEMS.register("hollow_bricks", () -> new BlockItem(HOLLOW_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> HOLLOW_BRICK_STAIRS = ModBlocks.BLOCKS.register("hollow_brick_stairs", () -> new StairBlock(() -> HOLLOW_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> HOLLOW_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("hollow_brick_stairs", () -> new BlockItem(HOLLOW_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> HOLLOW_BRICK_SLAB = ModBlocks.BLOCKS.register("hollow_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> HOLLOW_BRICK_SLAB_ITEM = ModItems.ITEMS.register("hollow_brick_slab", () -> new BlockItem(HOLLOW_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> HOLLOW_SIGIL_STONE = ModBlocks.BLOCKS.register("hollow_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> HOLLOW_SIGIL_STONE_ITEM = ModItems.ITEMS.register("hollow_sigil_stone", () -> new BlockItem(HOLLOW_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> HOLLOW_SIGIL_LAMP = ModBlocks.BLOCKS.register("hollow_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> HOLLOW_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("hollow_sigil_lamp", () -> new BlockItem(HOLLOW_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> DROWNED_BRICKS = ModBlocks.BLOCKS.register("drowned_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> DROWNED_BRICKS_ITEM = ModItems.ITEMS.register("drowned_bricks", () -> new BlockItem(DROWNED_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> DROWNED_BRICK_STAIRS = ModBlocks.BLOCKS.register("drowned_brick_stairs", () -> new StairBlock(() -> DROWNED_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> DROWNED_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("drowned_brick_stairs", () -> new BlockItem(DROWNED_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> DROWNED_BRICK_SLAB = ModBlocks.BLOCKS.register("drowned_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> DROWNED_BRICK_SLAB_ITEM = ModItems.ITEMS.register("drowned_brick_slab", () -> new BlockItem(DROWNED_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> DROWNED_SIGIL_STONE = ModBlocks.BLOCKS.register("drowned_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> DROWNED_SIGIL_STONE_ITEM = ModItems.ITEMS.register("drowned_sigil_stone", () -> new BlockItem(DROWNED_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> DROWNED_SIGIL_LAMP = ModBlocks.BLOCKS.register("drowned_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_NYLIUM).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> DROWNED_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("drowned_sigil_lamp", () -> new BlockItem(DROWNED_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> PALE_BRICKS = ModBlocks.BLOCKS.register("pale_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.ICE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> PALE_BRICKS_ITEM = ModItems.ITEMS.register("pale_bricks", () -> new BlockItem(PALE_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> PALE_BRICK_STAIRS = ModBlocks.BLOCKS.register("pale_brick_stairs", () -> new StairBlock(() -> PALE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.ICE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> PALE_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("pale_brick_stairs", () -> new BlockItem(PALE_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> PALE_BRICK_SLAB = ModBlocks.BLOCKS.register("pale_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.ICE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> PALE_BRICK_SLAB_ITEM = ModItems.ITEMS.register("pale_brick_slab", () -> new BlockItem(PALE_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> PALE_SIGIL_STONE = ModBlocks.BLOCKS.register("pale_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.ICE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> PALE_SIGIL_STONE_ITEM = ModItems.ITEMS.register("pale_sigil_stone", () -> new BlockItem(PALE_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> PALE_SIGIL_LAMP = ModBlocks.BLOCKS.register("pale_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.ICE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> PALE_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("pale_sigil_lamp", () -> new BlockItem(PALE_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> SCARLET_BRICKS = ModBlocks.BLOCKS.register("scarlet_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SCARLET_BRICKS_ITEM = ModItems.ITEMS.register("scarlet_bricks", () -> new BlockItem(SCARLET_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> SCARLET_BRICK_STAIRS = ModBlocks.BLOCKS.register("scarlet_brick_stairs", () -> new StairBlock(() -> SCARLET_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SCARLET_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("scarlet_brick_stairs", () -> new BlockItem(SCARLET_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> SCARLET_BRICK_SLAB = ModBlocks.BLOCKS.register("scarlet_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SCARLET_BRICK_SLAB_ITEM = ModItems.ITEMS.register("scarlet_brick_slab", () -> new BlockItem(SCARLET_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> SCARLET_SIGIL_STONE = ModBlocks.BLOCKS.register("scarlet_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> SCARLET_SIGIL_STONE_ITEM = ModItems.ITEMS.register("scarlet_sigil_stone", () -> new BlockItem(SCARLET_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> SCARLET_SIGIL_LAMP = ModBlocks.BLOCKS.register("scarlet_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> SCARLET_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("scarlet_sigil_lamp", () -> new BlockItem(SCARLET_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> CLOCKWORK_BRICKS = ModBlocks.BLOCKS.register("clockwork_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> CLOCKWORK_BRICKS_ITEM = ModItems.ITEMS.register("clockwork_bricks", () -> new BlockItem(CLOCKWORK_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> CLOCKWORK_BRICK_STAIRS = ModBlocks.BLOCKS.register("clockwork_brick_stairs", () -> new StairBlock(() -> CLOCKWORK_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> CLOCKWORK_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("clockwork_brick_stairs", () -> new BlockItem(CLOCKWORK_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> CLOCKWORK_BRICK_SLAB = ModBlocks.BLOCKS.register("clockwork_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> CLOCKWORK_BRICK_SLAB_ITEM = ModItems.ITEMS.register("clockwork_brick_slab", () -> new BlockItem(CLOCKWORK_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> CLOCKWORK_SIGIL_STONE = ModBlocks.BLOCKS.register("clockwork_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> CLOCKWORK_SIGIL_STONE_ITEM = ModItems.ITEMS.register("clockwork_sigil_stone", () -> new BlockItem(CLOCKWORK_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> CLOCKWORK_SIGIL_LAMP = ModBlocks.BLOCKS.register("clockwork_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> CLOCKWORK_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("clockwork_sigil_lamp", () -> new BlockItem(CLOCKWORK_SIGIL_LAMP.get(), new Item.Properties()));
    public static final RegistryObject<Block> MYCELIAL_BRICKS = ModBlocks.BLOCKS.register("mycelial_bricks", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> MYCELIAL_BRICKS_ITEM = ModItems.ITEMS.register("mycelial_bricks", () -> new BlockItem(MYCELIAL_BRICKS.get(), new Item.Properties()));
    public static final RegistryObject<Block> MYCELIAL_BRICK_STAIRS = ModBlocks.BLOCKS.register("mycelial_brick_stairs", () -> new StairBlock(() -> MYCELIAL_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> MYCELIAL_BRICK_STAIRS_ITEM = ModItems.ITEMS.register("mycelial_brick_stairs", () -> new BlockItem(MYCELIAL_BRICK_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Block> MYCELIAL_BRICK_SLAB = ModBlocks.BLOCKS.register("mycelial_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> MYCELIAL_BRICK_SLAB_ITEM = ModItems.ITEMS.register("mycelial_brick_slab", () -> new BlockItem(MYCELIAL_BRICK_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Block> MYCELIAL_SIGIL_STONE = ModBlocks.BLOCKS.register("mycelial_sigil_stone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Item> MYCELIAL_SIGIL_STONE_ITEM = ModItems.ITEMS.register("mycelial_sigil_stone", () -> new BlockItem(MYCELIAL_SIGIL_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Block> MYCELIAL_SIGIL_LAMP = ModBlocks.BLOCKS.register("mycelial_sigil_lamp", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).strength(2.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).lightLevel(s -> 15)));
    public static final RegistryObject<Item> MYCELIAL_SIGIL_LAMP_ITEM = ModItems.ITEMS.register("mycelial_sigil_lamp", () -> new BlockItem(MYCELIAL_SIGIL_LAMP.get(), new Item.Properties()));

    public static final RegistryObject<PaintingVariant> PAINTING_MOSSBACK_TITAN = PAINTINGS.register("mossback_titan", () -> new PaintingVariant(64, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_TEMPEST_ROC = PAINTINGS.register("tempest_roc", () -> new PaintingVariant(64, 48));
    public static final RegistryObject<PaintingVariant> PAINTING_HOLLOW_KING = PAINTINGS.register("hollow_king", () -> new PaintingVariant(64, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_VORATH = PAINTINGS.register("vorath", () -> new PaintingVariant(64, 48));
    public static final RegistryObject<PaintingVariant> PAINTING_WHITE_SILENCE = PAINTINGS.register("white_silence", () -> new PaintingVariant(48, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_KHARZUL = PAINTINGS.register("kharzul", () -> new PaintingVariant(48, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_VEXOR = PAINTINGS.register("vexor", () -> new PaintingVariant(64, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_BLOOM_MOTHER = PAINTINGS.register("bloom_mother", () -> new PaintingVariant(64, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_UNMAKER = PAINTINGS.register("unmaker", () -> new PaintingVariant(64, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_THE_LAST_REALM = PAINTINGS.register("the_last_realm", () -> new PaintingVariant(64, 64));
    public static final RegistryObject<PaintingVariant> PAINTING_THE_SHATTERED_CROWN = PAINTINGS.register("the_shattered_crown", () -> new PaintingVariant(64, 48));
    public static final RegistryObject<PaintingVariant> PAINTING_THE_CONVERGENCE_GATE = PAINTINGS.register("the_convergence_gate", () -> new PaintingVariant(48, 48));

    /** Touches the class so the registrations above happen before the registers fire. */
    public static void init() {}

    /** Everything here for the creative tab, in order. */
    public static List<RegistryObject<Item>> tabItems() {
        return List.of(WAYFINDERS_LODESTAR, AURELIAN_BESTIARY, GROVE_BRICKS_ITEM, GROVE_BRICK_STAIRS_ITEM, GROVE_BRICK_SLAB_ITEM, GROVE_SIGIL_STONE_ITEM, GROVE_SIGIL_LAMP_ITEM, SKYREACH_BRICKS_ITEM, SKYREACH_BRICK_STAIRS_ITEM, SKYREACH_BRICK_SLAB_ITEM, SKYREACH_SIGIL_STONE_ITEM, SKYREACH_SIGIL_LAMP_ITEM, HOLLOW_BRICKS_ITEM, HOLLOW_BRICK_STAIRS_ITEM, HOLLOW_BRICK_SLAB_ITEM, HOLLOW_SIGIL_STONE_ITEM, HOLLOW_SIGIL_LAMP_ITEM, DROWNED_BRICKS_ITEM, DROWNED_BRICK_STAIRS_ITEM, DROWNED_BRICK_SLAB_ITEM, DROWNED_SIGIL_STONE_ITEM, DROWNED_SIGIL_LAMP_ITEM, PALE_BRICKS_ITEM, PALE_BRICK_STAIRS_ITEM, PALE_BRICK_SLAB_ITEM, PALE_SIGIL_STONE_ITEM, PALE_SIGIL_LAMP_ITEM, SCARLET_BRICKS_ITEM, SCARLET_BRICK_STAIRS_ITEM, SCARLET_BRICK_SLAB_ITEM, SCARLET_SIGIL_STONE_ITEM, SCARLET_SIGIL_LAMP_ITEM, CLOCKWORK_BRICKS_ITEM, CLOCKWORK_BRICK_STAIRS_ITEM, CLOCKWORK_BRICK_SLAB_ITEM, CLOCKWORK_SIGIL_STONE_ITEM, CLOCKWORK_SIGIL_LAMP_ITEM, MYCELIAL_BRICKS_ITEM, MYCELIAL_BRICK_STAIRS_ITEM, MYCELIAL_BRICK_SLAB_ITEM, MYCELIAL_SIGIL_STONE_ITEM, MYCELIAL_SIGIL_LAMP_ITEM);
    }
}
