package com.aurelia.registry;

import com.aurelia.AureliaMod;
import com.aurelia.entity.Lieutenant;
import com.aurelia.entity.LieutenantKind;
import java.util.EnumMap;
import java.util.Map;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.registries.RegistryObject;

/** GENERATED by gen_lieutenants.py. The lieutenants' entity types and spawn eggs, registered on the mod's own registers. */
public final class LieutenantEntities {
    private LieutenantEntities() {}

    public static final Map<LieutenantKind, RegistryObject<EntityType<Lieutenant>>> TYPES = new EnumMap<>(LieutenantKind.class);
    public static final Map<LieutenantKind, RegistryObject<Item>> EGGS = new EnumMap<>(LieutenantKind.class);
    private static final int[][] EGG_COLORS = {{0x2E4A22, 0x7CFF5A}, {0x2E4A22, 0x7CFF5A}, {0x2E4A22, 0x7CFF5A}, {0x4A5A74, 0x9EE8FF}, {0x4A5A74, 0x9EE8FF}, {0x4A5A74, 0x9EE8FF}, {0x2A1414, 0xFF7A22}, {0x2A1414, 0xFF7A22}, {0x2A1414, 0xFF7A22}, {0x1E3E44, 0x5AF0D8}, {0x1E3E44, 0x5AF0D8}, {0x1E3E44, 0x5AF0D8}, {0xDDE6F2, 0x6A86C8}, {0xDDE6F2, 0x6A86C8}, {0xDDE6F2, 0x6A86C8}, {0x8C1E24, 0xFFC040}, {0x8C1E24, 0xFFC040}, {0x8C1E24, 0xFFC040}, {0x34323C, 0xC296FF}, {0x34323C, 0xC296FF}, {0x34323C, 0xC296FF}, {0x8A6A7C, 0xFF5AE6}, {0x8A6A7C, 0xFF5AE6}, {0x8A6A7C, 0xFF5AE6}, {0xE2DAC8, 0x1C1A22}, {0xE2DAC8, 0x1C1A22}};

    static {
        for (LieutenantKind kind : LieutenantKind.values()) {
            TYPES.put(kind, ModEntities.ENTITIES.register(kind.id, () -> EntityType.Builder.<Lieutenant>of((type, level) -> new Lieutenant(type, level, kind),
                    MobCategory.MONSTER).sized(kind.width, kind.height).clientTrackingRange(12).fireImmune()
                    .build(new ResourceLocation(AureliaMod.MODID, kind.id).toString())));
            int[] c = EGG_COLORS[kind.ordinal()];
            EGGS.put(kind, ModItems.ITEMS.register(kind.id + "_spawn_egg", () -> new ForgeSpawnEggItem(TYPES.get(kind), c[0], c[1], new Item.Properties())));
        }
    }

    /** Touches the class so the registrations above happen before the registers fire. */
    public static void init() {}

    public static EntityType<Lieutenant> type(LieutenantKind kind) {
        RegistryObject<EntityType<Lieutenant>> ro = TYPES.get(kind);
        return ro != null && ro.isPresent() ? ro.get() : null;
    }

    public static void registerAttributes(EntityAttributeCreationEvent event) {
        for (LieutenantKind kind : LieutenantKind.values()) {
            event.put(TYPES.get(kind).get(), Lieutenant.attributes(kind).build());
        }
    }
}
