package com.aurelia.client;

import com.aurelia.AureliaMod;
import com.aurelia.entity.Lieutenant;
import com.aurelia.entity.LieutenantKind;
import com.aurelia.registry.LieutenantEntities;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraftforge.client.event.EntityRenderersEvent;

/** GENERATED by gen_lieutenants.py. The lieutenants' renderers: their box models from MobModels, their textures by id. */
public final class LieutenantRenderers {
    private LieutenantRenderers() {}

    private static void spec(EntityRenderersEvent.RegisterRenderers event, LieutenantKind kind, ModelLayerLocation layer, String[] names, String[] anims,
                             float shadow) {
        event.registerEntityRenderer(LieutenantEntities.TYPES.get(kind).get(), ctx -> new SpecRenderer<Lieutenant>(ctx, layer, names, anims, shadow, kind.id, kind.flying));
    }

    public static void register(EntityRenderersEvent.RegisterRenderers event) {
        spec(event, LieutenantKind.THORNMAW, MobModels.THORNMAW, MobModels.THORNMAW_NAMES, MobModels.THORNMAW_ANIMS, MobModels.THORNMAW_SHADOW);
        spec(event, LieutenantKind.HOLLOWBARK, MobModels.HOLLOWBARK, MobModels.HOLLOWBARK_NAMES, MobModels.HOLLOWBARK_ANIMS, MobModels.HOLLOWBARK_SHADOW);
        spec(event, LieutenantKind.ROT_MATRON, MobModels.ROT_MATRON, MobModels.ROT_MATRON_NAMES, MobModels.ROT_MATRON_ANIMS, MobModels.ROT_MATRON_SHADOW);
        spec(event, LieutenantKind.GALECLAW, MobModels.GALECLAW, MobModels.GALECLAW_NAMES, MobModels.GALECLAW_ANIMS, MobModels.GALECLAW_SHADOW);
        spec(event, LieutenantKind.THUNDER_COLOSSUS, MobModels.THUNDER_COLOSSUS, MobModels.THUNDER_COLOSSUS_NAMES, MobModels.THUNDER_COLOSSUS_ANIMS, MobModels.THUNDER_COLOSSUS_SHADOW);
        spec(event, LieutenantKind.SQUALL_SERAPH, MobModels.SQUALL_SERAPH, MobModels.SQUALL_SERAPH_NAMES, MobModels.SQUALL_SERAPH_ANIMS, MobModels.SQUALL_SERAPH_SHADOW);
        spec(event, LieutenantKind.CINDERJAW, MobModels.CINDERJAW, MobModels.CINDERJAW_NAMES, MobModels.CINDERJAW_ANIMS, MobModels.CINDERJAW_SHADOW);
        spec(event, LieutenantKind.CHAINWARDEN, MobModels.CHAINWARDEN, MobModels.CHAINWARDEN_NAMES, MobModels.CHAINWARDEN_ANIMS, MobModels.CHAINWARDEN_SHADOW);
        spec(event, LieutenantKind.ASHEN_CHOIR, MobModels.ASHEN_CHOIR, MobModels.ASHEN_CHOIR_NAMES, MobModels.ASHEN_CHOIR_ANIMS, MobModels.ASHEN_CHOIR_SHADOW);
        spec(event, LieutenantKind.REEF_CRUSHER, MobModels.REEF_CRUSHER, MobModels.REEF_CRUSHER_NAMES, MobModels.REEF_CRUSHER_ANIMS, MobModels.REEF_CRUSHER_SHADOW);
        spec(event, LieutenantKind.DROWNED_ADMIRAL, MobModels.DROWNED_ADMIRAL, MobModels.DROWNED_ADMIRAL_NAMES, MobModels.DROWNED_ADMIRAL_ANIMS, MobModels.DROWNED_ADMIRAL_SHADOW);
        spec(event, LieutenantKind.ABYSSAL_SIREN, MobModels.ABYSSAL_SIREN, MobModels.ABYSSAL_SIREN_NAMES, MobModels.ABYSSAL_SIREN_ANIMS, MobModels.ABYSSAL_SIREN_SHADOW);
        spec(event, LieutenantKind.FROSTMAW, MobModels.FROSTMAW, MobModels.FROSTMAW_NAMES, MobModels.FROSTMAW_ANIMS, MobModels.FROSTMAW_SHADOW);
        spec(event, LieutenantKind.RIME_KNIGHT, MobModels.RIME_KNIGHT, MobModels.RIME_KNIGHT_NAMES, MobModels.RIME_KNIGHT_ANIMS, MobModels.RIME_KNIGHT_SHADOW);
        spec(event, LieutenantKind.THE_MOURNER, MobModels.THE_MOURNER, MobModels.THE_MOURNER_NAMES, MobModels.THE_MOURNER_ANIMS, MobModels.THE_MOURNER_SHADOW);
        spec(event, LieutenantKind.DUNE_TYRANT, MobModels.DUNE_TYRANT, MobModels.DUNE_TYRANT_NAMES, MobModels.DUNE_TYRANT_ANIMS, MobModels.DUNE_TYRANT_SHADOW);
        spec(event, LieutenantKind.SAND_PHARAOH, MobModels.SAND_PHARAOH, MobModels.SAND_PHARAOH_NAMES, MobModels.SAND_PHARAOH_ANIMS, MobModels.SAND_PHARAOH_SHADOW);
        spec(event, LieutenantKind.GLASS_DJINN, MobModels.GLASS_DJINN, MobModels.GLASS_DJINN_NAMES, MobModels.GLASS_DJINN_ANIMS, MobModels.GLASS_DJINN_SHADOW);
        spec(event, LieutenantKind.PENDULUM_BUTCHER, MobModels.PENDULUM_BUTCHER, MobModels.PENDULUM_BUTCHER_NAMES, MobModels.PENDULUM_BUTCHER_ANIMS, MobModels.PENDULUM_BUTCHER_SHADOW);
        spec(event, LieutenantKind.GEARWYRM, MobModels.GEARWYRM, MobModels.GEARWYRM_NAMES, MobModels.GEARWYRM_ANIMS, MobModels.GEARWYRM_SHADOW);
        spec(event, LieutenantKind.HOURLESS_ORACLE, MobModels.HOURLESS_ORACLE, MobModels.HOURLESS_ORACLE_NAMES, MobModels.HOURLESS_ORACLE_ANIMS, MobModels.HOURLESS_ORACLE_SHADOW);
        spec(event, LieutenantKind.ROT_BEHEMOTH, MobModels.ROT_BEHEMOTH, MobModels.ROT_BEHEMOTH_NAMES, MobModels.ROT_BEHEMOTH_ANIMS, MobModels.ROT_BEHEMOTH_SHADOW);
        spec(event, LieutenantKind.PALE_GARDENER, MobModels.PALE_GARDENER, MobModels.PALE_GARDENER_NAMES, MobModels.PALE_GARDENER_ANIMS, MobModels.PALE_GARDENER_SHADOW);
        spec(event, LieutenantKind.LUMEN_HORROR, MobModels.LUMEN_HORROR, MobModels.LUMEN_HORROR_NAMES, MobModels.LUMEN_HORROR_ANIMS, MobModels.LUMEN_HORROR_SHADOW);
        spec(event, LieutenantKind.HERALD_OF_RUIN, MobModels.HERALD_OF_RUIN, MobModels.HERALD_OF_RUIN_NAMES, MobModels.HERALD_OF_RUIN_ANIMS, MobModels.HERALD_OF_RUIN_SHADOW);
        spec(event, LieutenantKind.HERALD_OF_SILENCE, MobModels.HERALD_OF_SILENCE, MobModels.HERALD_OF_SILENCE_NAMES, MobModels.HERALD_OF_SILENCE_ANIMS, MobModels.HERALD_OF_SILENCE_SHADOW);
    }
}
