"""Emit MobModels.java (generated) from mobspecs."""
import mobspecs

OUT = '/home/claude/aurelia/src/main/java/com/aurelia/client/MobModels.java'


def f(v):
    return f'{v:.3f}F'


built = mobspecs.build_all()
lines = ['package com.aurelia.client;', '',
         'import com.aurelia.AureliaMod;',
         'import net.minecraft.client.model.geom.ModelLayerLocation;',
         'import net.minecraft.client.model.geom.PartPose;',
         'import net.minecraft.client.model.geom.builders.CubeListBuilder;',
         'import net.minecraft.client.model.geom.builders.LayerDefinition;',
         'import net.minecraft.client.model.geom.builders.MeshDefinition;',
         'import net.minecraft.client.model.geom.builders.PartDefinition;',
         'import net.minecraft.resources.ResourceLocation;',
         'import net.minecraftforge.client.event.EntityRenderersEvent;', '',
         '/** GENERATED by gen_models.py from mobspecs.py. Do not edit by hand. */',
         'public final class MobModels {',
         '    private MobModels() {}', '',
         '    private static ModelLayerLocation layer(String name) {',
         '        return new ModelLayerLocation(new ResourceLocation(AureliaMod.MODID, name), "main");',
         '    }', '']
registrations = []
for key, b in built.items():
    const = key.upper()
    parts = b['parts']
    byname = {p['name']: p for p in parts}
    assert len(byname) == len(parts), f'duplicate part names in {key}'
    order = {p['name']: i for i, p in enumerate(parts)}
    for p in parts:
        if p.get('parent'):
            assert p['parent'] in byname, f"{key}: unknown parent {p['parent']} for {p['name']}"
            assert order[p['parent']] < order[p['name']], f"{key}: parent {p['parent']} defined after child {p['name']}"

    def path(p):
        return p['name'] if not p.get('parent') else path(byname[p['parent']]) + '/' + p['name']
    has_children = {p['parent'] for p in parts if p.get('parent')}
    names = ', '.join(f'"{path(p)}"' for p in parts)
    anims = ', '.join(f'"{p["anim"]}"' for p in parts)
    lines.append(f'    public static final ModelLayerLocation {const} = layer("{key}");')
    lines.append(f'    public static final String[] {const}_NAMES = {{{names}}};')
    lines.append(f'    public static final String[] {const}_ANIMS = {{{anims}}};')
    lines.append(f'    public static final float {const}_SHADOW = {f(b["shadow"])};')
    lines.append(f'    public static LayerDefinition {key}() {{')
    lines.append('        MeshDefinition mesh = new MeshDefinition();')
    lines.append('        PartDefinition root = mesh.getRoot();')
    for p in parts:
        w, h, d = p['size']
        x0, y0, z0 = p['origin']
        px, py, pz = p['pivot']
        rx, ry, rz = p['rot']
        u, v = p['uv']
        # my space (y up, front +z) -> vanilla model space (y down, front -z); top-level parts also drop by the 24-unit root offset
        vx0, vy0, vz0 = x0, -(y0 + h), -(z0 + d)
        vpx, vpy, vpz = (px, -py, -pz) if p.get('parent') else (px, 24 - py, -pz)
        owner = f'p_{p["parent"]}' if p.get('parent') else 'root'
        decl = f'PartDefinition p_{p["name"]} = ' if p['name'] in has_children else ''
        lines.append(f'        {decl}{owner}.addOrReplaceChild("{p["name"]}", CubeListBuilder.create().texOffs({u}, {v})'
                     f'.addBox({f(vx0)}, {f(vy0)}, {f(vz0)}, {w}.0F, {h}.0F, {d}.0F), '
                     f'PartPose.offsetAndRotation({f(vpx)}, {f(vpy)}, {f(vpz)}, {f(rx)}, {f(-ry)}, {f(-rz)}));')
    lines.append(f'        return LayerDefinition.create(mesh, {b["sheet"]}, {b["sheet"]});')
    lines.append('    }')
    lines.append('')
    registrations.append(f'        event.registerLayerDefinition({const}, MobModels::{key});')
lines.append('    public static void register(EntityRenderersEvent.RegisterLayerDefinitions event) {')
lines += registrations
lines.append('    }')
lines.append('}')
open(OUT, 'w').write('\n'.join(lines) + '\n')
print('wrote', OUT, 'for', len(built), 'models')
