"""Writes the lieutenants' Java and data from lieutenants.py:
  entity/LieutenantKind.java       one constant per lieutenant: realm, slot, stats, body, abilities, minion, lines
  registry/LieutenantEntities.java their entity types and spawn eggs, and their attributes
  client/LieutenantRenderers.java  their renderers (models come from MobModels, written by gen_models.py)
and their names in the lang file, their spawn egg item models, and the Lair Seal block's assets."""
import json
import os

import paths
from lieutenants import LIEUTENANTS, REALM_ORDER, stats

J = paths.JAVA
A = paths.RES + '/assets/aurelia'
BAR = {'grove': 'GREEN', 'skyreach': 'BLUE', 'hollow': 'RED', 'drowned': 'BLUE', 'pale': 'WHITE', 'scarlet': 'RED', 'clockwork': 'YELLOW',
       'mycelial': 'PINK', 'last': 'PURPLE'}
EGG = {'grove': (0x2E4A22, 0x7CFF5A), 'skyreach': (0x4A5A74, 0x9EE8FF), 'hollow': (0x2A1414, 0xFF7A22), 'drowned': (0x1E3E44, 0x5AF0D8),
       'pale': (0xDDE6F2, 0x6A86C8), 'scarlet': (0x8C1E24, 0xFFC040), 'clockwork': (0x34323C, 0xC296FF), 'mycelial': (0x8A6A7C, 0xFF5AE6),
       'last': (0xE2DAC8, 0x1C1A22)}


def jstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def slot_of(lt):
    return [x['id'] for x in LIEUTENANTS if x['realm'] == lt['realm']].index(lt['id'])


def kind_java():
    rows = []
    for lt in LIEUTENANTS:
        hp, dmg = stats(lt)
        abil = ', '.join(f'Lieutenant.Ability.{a}' for a in lt['abilities'])
        minion = jstr(lt['minion']) if lt['minion'] else 'null'
        rows.append(f'    {lt["id"].upper()}({jstr(lt["id"])}, Realm.{lt["realm"].upper()}, {slot_of(lt)}, {jstr(lt["title"])}, {str(lt["body"] == "flyer").lower()}, '
                    f'{hp}, {dmg}, {lt["speed"]}, {lt["size"][0]}f, {lt["size"][1]}f, BossEvent.BossBarColor.{BAR[lt["realm"]]}, {minion},\n'
                    f'            new Lieutenant.Ability[] {{{abil}}},\n'
                    f'            {jstr(lt["awaken"])},\n            {jstr(lt["death"])})')
    return f'''package com.aurelia.entity;

import com.aurelia.registry.LieutenantEntities;
import com.aurelia.world.Realm;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nullable;
import net.minecraft.world.BossEvent;
import net.minecraft.world.entity.EntityType;

/** GENERATED by gen_lieutenants.py from tools/lieutenants.py. Every Warden's lieutenants, and the Unmaker's two Heralds. */
public enum LieutenantKind {{
{(','+chr(10)).join(rows)};

    public final String id;
    public final Realm realm;
    /** Which of its realm's lairs it holds: 0, 1 or 2. */
    public final int slot;
    public final String title;
    public final boolean flying;
    public final double health;
    public final double damage;
    public final double speed;
    public final float width;
    public final float height;
    private final BossEvent.BossBarColor bar;
    @Nullable
    public final String minion;
    public final Lieutenant.Ability[] abilities;
    public final String awakenLine;
    public final String deathLine;

    LieutenantKind(String id, Realm realm, int slot, String title, boolean flying, double health, double damage, double speed, float width,
                   float height, BossEvent.BossBarColor bar, @Nullable String minion, Lieutenant.Ability[] abilities, String awakenLine,
                   String deathLine) {{
        this.id = id;
        this.realm = realm;
        this.slot = slot;
        this.title = title;
        this.flying = flying;
        this.health = health;
        this.damage = damage;
        this.speed = speed;
        this.width = width;
        this.height = height;
        this.bar = bar;
        this.minion = minion;
        this.abilities = abilities;
        this.awakenLine = awakenLine;
        this.deathLine = deathLine;
    }}

    public BossEvent.BossBarColor barColor() {{
        return this.bar;
    }}

    /** The lieutenants of a realm, in lair order. Empty for a realm without any. */
    public static List<LieutenantKind> of(Realm realm) {{
        List<LieutenantKind> out = new ArrayList<>();
        for (LieutenantKind k : values()) {{
            if (k.realm == realm) {{
                out.add(k);
            }}
        }}
        return out;
    }}

    @Nullable
    public static LieutenantKind of(Realm realm, int slot) {{
        for (LieutenantKind k : values()) {{
            if (k.realm == realm && k.slot == slot) {{
                return k;
            }}
        }}
        return null;
    }}

    @Nullable
    public static LieutenantKind byType(EntityType<?> type) {{
        for (LieutenantKind k : values()) {{
            if (LieutenantEntities.type(k) == type) {{
                return k;
            }}
        }}
        return null;
    }}
}}
'''


def entities_java():
    return '''package com.aurelia.registry;

import com.aurelia.AureliaMod;
import com.aurelia.entity.Lieutenant;
import com.aurelia.entity.LieutenantKind;
import java.util.EnumMap;
import java.util.Map;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.registries.RegistryObject;

/** GENERATED by gen_lieutenants.py. The lieutenants' entity types and spawn eggs, registered on the mod's own registers. */
public final class LieutenantEntities {
    private LieutenantEntities() {}

    public static final Map<LieutenantKind, RegistryObject<EntityType<Lieutenant>>> TYPES = new EnumMap<>(LieutenantKind.class);
    public static final Map<LieutenantKind, RegistryObject<Item>> EGGS = new EnumMap<>(LieutenantKind.class);
    private static final int[][] EGG_COLORS = {''' + ', '.join('{0x%06X, 0x%06X}' % EGG[lt['realm']] for lt in LIEUTENANTS) + '''};

    static {
        for (LieutenantKind kind : LieutenantKind.values()) {
            TYPES.put(kind, ModEntities.ENTITIES.register(kind.id, () -> EntityType.Builder.<Lieutenant>of((type, level) -> new Lieutenant(type, level, kind),
                    MobCategory.MONSTER).sized(kind.width, kind.height).clientTrackingRange(12).fireImmune()
                    .build(new ResourceLocation(AureliaMod.MODID, kind.id).toString())));
            int[] c = EGG_COLORS[kind.ordinal()];
            EGGS.put(kind, ModItems.ITEMS.register(kind.id + "_spawn_egg", () -> new ForgeSpawnEggItem(TYPES.get(kind), c[0], c[1], new Item.Properties())));
        }
    }

    /** Touches the class so the registrations above happen before the registers fire. */
    public static void init() {}

    public static EntityType<Lieutenant> type(LieutenantKind kind) {
        RegistryObject<EntityType<Lieutenant>> ro = TYPES.get(kind);
        return ro != null && ro.isPresent() ? ro.get() : null;
    }

    public static void registerAttributes(EntityAttributeCreationEvent event) {
        for (LieutenantKind kind : LieutenantKind.values()) {
            event.put(TYPES.get(kind).get(), Lieutenant.attributes(kind).build());
        }
    }
}
'''


def renderers_java():
    lines = []
    for lt in LIEUTENANTS:
        c = lt['id'].upper()
        lines.append(f'        spec(event, LieutenantKind.{c}, MobModels.{c}, MobModels.{c}_NAMES, MobModels.{c}_ANIMS, MobModels.{c}_SHADOW);')
    return '''package com.aurelia.client;

import com.aurelia.AureliaMod;
import com.aurelia.entity.Lieutenant;
import com.aurelia.entity.LieutenantKind;
import com.aurelia.registry.LieutenantEntities;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraftforge.client.event.EntityRenderersEvent;

/** GENERATED by gen_lieutenants.py. The lieutenants' renderers: their box models from MobModels, their textures by id. */
public final class LieutenantRenderers {
    private LieutenantRenderers() {}

    private static void spec(EntityRenderersEvent.RegisterRenderers event, LieutenantKind kind, ModelLayerLocation layer, String[] names, String[] anims,
                             float shadow) {
        event.registerEntityRenderer(LieutenantEntities.TYPES.get(kind).get(), ctx -> new SpecRenderer<Lieutenant>(ctx, layer, names, anims, shadow, kind.id, kind.flying));
    }

    public static void register(EntityRenderersEvent.RegisterRenderers event) {
''' + '\n'.join(lines) + '''
    }
}
'''


def seal_assets():
    """The Lair Seal: black stone carved with a ring of runes round a violet eye, the same for every slot."""
    from pixelart import Sprite
    s = Sprite(16, 77)
    s.rect(-1, -1, 17, 17, 'deepslate')
    s.ellipse(8, 8, 6.5, 6.5, 'black')
    s.ellipse(8, 8, 5, 5, 'abyss')
    for k in range(8):
        import math
        a = k * math.pi / 4
        s.gem(8 + 5.8 * math.cos(a), 8 + 5.8 * math.sin(a), 0.9, 'gem_v')
    s.gem(8, 8, 2.6, 'void_p')
    s.render(outline=False, halo=False).save(f'{A}/textures/block/lair_seal.png')
    side = Sprite(16, 78)
    side.rect(-1, -1, 17, 17, 'deepslate')
    side.rect(-1, 6, 17, 9, 'black')
    for x in (2, 8, 14):
        side.gem(x, 7.5, 1.2, 'gem_v')
    side.render(outline=False, halo=False).save(f'{A}/textures/block/lair_seal_side.png')
    json.dump({'parent': 'minecraft:block/cube_bottom_top', 'textures': {'top': 'aurelia:block/lair_seal', 'bottom': 'minecraft:block/polished_deepslate',
               'side': 'aurelia:block/lair_seal_side'}}, open(f'{A}/models/block/lair_seal.json', 'w'), indent=2)
    json.dump({'variants': {f'slot={i}': {'model': 'aurelia:block/lair_seal'} for i in range(3)}}, open(f'{A}/blockstates/lair_seal.json', 'w'), indent=2)
    json.dump({'parent': 'aurelia:block/lair_seal'}, open(f'{A}/models/item/lair_seal.json', 'w'), indent=2)
    lt = paths.RES + '/data/aurelia/loot_tables/blocks/lair_seal.json'
    json.dump({'type': 'minecraft:block', 'pools': []}, open(lt, 'w'), indent=2)


def main():
    open(f'{J}/entity/LieutenantKind.java', 'w').write(kind_java())
    open(f'{J}/registry/LieutenantEntities.java', 'w').write(entities_java())
    open(f'{J}/client/LieutenantRenderers.java', 'w').write(renderers_java())
    lang_p = f'{A}/lang/en_us.json'
    lang = json.load(open(lang_p, encoding='utf-8'))
    for lt in LIEUTENANTS:
        lang[f'entity.aurelia.{lt["id"]}'] = lt['name']
        lang[f'item.aurelia.{lt["id"]}_spawn_egg'] = f'{lt["name"]} Spawn Egg'
        os.makedirs(f'{A}/models/item', exist_ok=True)
        json.dump({'parent': 'minecraft:item/template_spawn_egg'}, open(f'{A}/models/item/{lt["id"]}_spawn_egg.json', 'w'), indent=2)
    lang['block.aurelia.lair_seal'] = 'Lair Seal'
    seal_assets()
    json.dump(lang, open(lang_p, 'w', encoding='utf-8'), indent=2, ensure_ascii=False)
    print('lieutenants written:', len(LIEUTENANTS))


if __name__ == '__main__':
    main()
