"""Each realm's kit, defined once: its material, armor set, signature weapon, wildlife and food.
Used by gen_realm_kit.py (assets and data), mobs_act5.py (models) and the preview gallery. The Java mirrors these names."""

REALMS = ['grove', 'skyreach', 'hollow', 'drowned', 'pale', 'scarlet', 'clockwork', 'mycelial']

KIT = {
    'grove': dict(material='verdant_shard', block='verdant_block', armor='verdant', armor_name='Verdant',
                  palette=[(34, 60, 28), (70, 120, 46), (128, 190, 80), (210, 240, 150)], accent=(120, 255, 90),
                  bonus='Regeneration II; poison cannot touch you; anyone who strikes you takes 4 damage and is rooted. Green spores drift round you.',
                  weapon='thornroot_blade', weapon_name='Thornroot Blade', weapon_power='Roots the target (Slowness III), poisons it, and heals you a heart.', weapon_ability='Bramble Eruption: thorns tear up through the ground in a line ahead (10 damage, rooted). 8 s.',
                  critter='mossling', critter_name='Mossling', critter_desc='A slow little tortoise with a garden growing on its shell.',
                  food='verdant_fig', food_name='Verdant Fig', food_power='Regeneration for 5 seconds.', ore=None),
    'skyreach': dict(material='stormglass_shard', block='stormglass_block', armor='stormglass', armor_name='Stormglass',
                     palette=[(40, 70, 110), (90, 150, 210), (170, 220, 250), (240, 252, 255)], accent=(140, 230, 255),
                     bonus='Jump Boost III, Speed I, no fall damage; a third of those who strike you are struck by lightning. Sparks crackle round you.',
                     weapon='galecutter', weapon_name='Galecutter', weapon_power='Throws the target into the air with a crack of thunder.', weapon_ability='Tempest Dash: you are flung eight blocks forward and lightning strikes everything you pass (12 damage). 6 s.',
                     critter='cloud_ray', critter_name='Cloud Ray', critter_desc='A pale manta that swims through the open sky between islands.',
                     food='sky_jelly', food_name='Sky Jelly', food_power='Slow Falling for 15 seconds.', ore=None),
    'hollow': dict(material='emberheart', block='emberheart_block', armor='emberheart', armor_name='Emberheart',
                   palette=[(24, 18, 22), (60, 36, 34), (200, 80, 30), (255, 180, 70)], accent=(255, 130, 40),
                   bonus='Fire Resistance and Strength I; anyone who strikes you burns for 6 seconds. Embers rise off you.',
                   weapon='soulbrand', weapon_name='Soulbrand', weapon_power='Sets the target on fire and withers it.', weapon_ability='Soul Inferno: a ring of soul fire bursts out round you (14 damage, burning, thrown back). 10 s.',
                   critter='ember_beetle', critter_name='Ember Beetle', critter_desc='A black beetle that glows through the cracks in its shell.',
                   food='charred_morsel', food_name='Charred Morsel', food_power='Fire Resistance for 30 seconds.', ore=None),
    'drowned': dict(material='tidestone_shard', block='tidestone_block', armor='tidestone', armor_name='Tidestone',
                    palette=[(16, 50, 52), (40, 110, 104), (90, 190, 170), (190, 250, 230)], accent=(80, 240, 210),
                    bonus="Water Breathing; Dolphin's Grace, Conduit Power and Regeneration in water or rain. Bubbles stream off you.",
                    weapon='undertow_fang', weapon_name='Undertow Fang', weapon_power='Drags the target toward you; half again as hard in water.', weapon_ability='Maelstrom: every enemy within 12 blocks is dragged to you and half-drowned (8 damage, slowed). 10 s.',
                    critter='lantern_jelly', critter_name='Lantern Jelly', critter_desc='A glowing jellyfish that drifts in the drowned forests.',
                    food='glowing_gel', food_name='Glowing Gel', food_power='Water Breathing and Night Vision for 30 seconds.', ore=None),
    'pale': dict(material='rime_crystal', block='rime_block', armor='rime', armor_name='Rime',
                 palette=[(70, 90, 120), (140, 170, 210), (210, 230, 250), (250, 254, 255)], accent=(200, 240, 255),
                 bonus='Immune to freezing, walk on powder snow, Resistance I; water freezes under your feet; anyone who strikes you is frozen. Snow falls round you.',
                 weapon='hushblade', weapon_name='Hushblade', weapon_power='Freezes the target; strikes twice as hard from a crouch.', weapon_ability='Whiteout Step: you vanish and reappear behind whatever you are looking at, striking it (18 damage, frozen). 6 s.',
                 critter='frost_hare', critter_name='Frost Hare', critter_desc='A white hare that freezes still when it hears you.',
                 food='frost_hare_haunch', food_name='Frost Hare Haunch', food_power='Very filling.', ore=None),
    'scarlet': dict(material='sunglass_shard', block='sunglass_block', armor='sunglass', armor_name='Sunglass',
                    palette=[(80, 24, 18), (160, 50, 30), (230, 110, 50), (255, 210, 120)], accent=(255, 90, 60),
                    bonus='By day Haste II and Strength II, by night Night Vision; a third of arrows and projectiles glance off you. Sunlight glints round you.',
                    weapon='glass_reaper', weapon_name='Glass Reaper', weapon_power='Sweeps: half the blow cuts everything else within reach.', weapon_ability='Reaping Arc: one full turn of the scythe (16 damage to everything within 6 blocks). 8 s.',
                    critter='sand_skink', critter_name='Sand Skink', critter_desc='A red lizard that swims through the dunes.',
                    food='sunbaked_tail', food_name='Sunbaked Tail', food_power='Haste for 20 seconds.', ore=None),
    'clockwork': dict(material='chronite_shard', block='chronite_block', armor='chronite', armor_name='Chronite',
                      palette=[(30, 26, 40), (90, 60, 140), (180, 130, 60), (255, 220, 120)], accent=(180, 100, 255),
                      bonus='Speed II and Haste II. Borrowed Time: a killing blow throws you back to where you stood five seconds ago at half health instead (once every 90 s).',
                      weapon='second_hand', weapon_name='Second Hand', weapon_power='Very fast. Slows and weakens the target.', weapon_ability='Stop the Clock: every enemy within 12 blocks is frozen in time for 4 seconds. 15 s.',
                      critter='cogling', critter_name='Cogling', critter_desc='A brass clockwork beetle, ticking quietly as it wanders.',
                      food='tickberry', food_name='Tickberry', food_power='Speed for 20 seconds.', ore='chronite_ore'),
    'mycelial': dict(material='bloomspore', block='bloomspore_block', armor='bloomspore', armor_name='Bloomspore',
                     palette=[(50, 20, 60), (120, 40, 130), (210, 80, 200), (250, 200, 240)], accent=(255, 90, 230),
                     bonus='Night Vision; poison and wither cannot touch you; it feeds you when hungry; allies near you regenerate; anyone who strikes you is poisoned.',
                     weapon='spore_lash', weapon_name='Spore Lash', weapon_power='Poisons and sickens the target and everything near it.', weapon_ability='Bloom Burst: a cloud of spores bursts out (Poison III, nausea) and you heal for every enemy it catches. 10 s.',
                     critter='spore_puff', critter_name='Spore Puff', critter_desc='A floating puffball that sighs out glowing spores.',
                     food='puffcap', food_name='Puffcap', food_power='Saturation and Regeneration.', ore='bloomspore_ore'),
}
PIECES = ['helmet', 'chestplate', 'leggings', 'boots']
