package com.aurelia.entity;

import com.aurelia.registry.LieutenantEntities;
import com.aurelia.world.Realm;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nullable;
import net.minecraft.world.BossEvent;
import net.minecraft.world.entity.EntityType;

/** GENERATED by gen_lieutenants.py from tools/lieutenants.py. Every Warden's lieutenants, and the Unmaker's two Heralds. */
public enum LieutenantKind {
    THORNMAW("thornmaw", Realm.GROVE, 0, "the Briar Hound", false, 700, 10, 0.34, 2.6f, 2.4f, BossEvent.BossBarColor.GREEN, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.CHARGE, Lieutenant.Ability.LEAP, Lieutenant.Ability.ROOT},
            "Something vast shakes the thorns from its back.",
            "The briars go still, and the hound with them."),
    HOLLOWBARK("hollowbark", Realm.GROVE, 1, "the Rotting Ent", false, 900, 10, 0.22, 2.2f, 6.2f, BossEvent.BossBarColor.GREEN, "aurelia:grove_ant",
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.SUMMON, Lieutenant.Ability.ZONE},
            "The dead tree opens its eyes.",
            "Old Hollowbark falls, and does not get up."),
    ROT_MATRON("rot_matron", Realm.GROVE, 2, "Mother of the Undergrowth", false, 700, 10, 0.3, 3.4f, 1.9f, BossEvent.BossBarColor.GREEN, "aurelia:rootstalker",
            new Lieutenant.Ability[] {Lieutenant.Ability.VOLLEY, Lieutenant.Ability.PULL, Lieutenant.Ability.SUMMON},
            "Eight eyes open in the dark under the roots.",
            "The Rot Matron curls up and dies."),
    GALECLAW("galeclaw", Realm.SKYREACH, 0, "the Storm Harrier", true, 750, 11, 0.3, 3.2f, 1.7f, BossEvent.BossBarColor.BLUE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.CHARGE, Lieutenant.Ability.BOLT, Lieutenant.Ability.STORM},
            "A shriek splits the clouds.",
            "Galeclaw tumbles out of the sky."),
    THUNDER_COLOSSUS("thunder_colossus", Realm.SKYREACH, 1, "Keeper of the Spire", false, 1050, 11, 0.2, 2.6f, 6.6f, BossEvent.BossBarColor.BLUE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.STORM, Lieutenant.Ability.BULWARK},
            "The stone giant draws a breath of thunder.",
            "The Colossus cracks, and the storm in it leaks away."),
    SQUALL_SERAPH("squall_seraph", Realm.SKYREACH, 2, "the Wind that Judges", true, 750, 11, 0.32, 1.6f, 3.6f, BossEvent.BossBarColor.BLUE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.BLINK, Lieutenant.Ability.VOLLEY, Lieutenant.Ability.PULL},
            "Wings unfold above you, white and cold.",
            "The Seraph scatters into sleet."),
    CINDERJAW("cinderjaw", Realm.HOLLOW, 0, "Hound of the Pit", false, 1150, 13, 0.36, 2.8f, 2.6f, BossEvent.BossBarColor.RED, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.CHARGE, Lieutenant.Ability.NOVA, Lieutenant.Ability.LEAP},
            "The lava stirs, and stands up.",
            "Cinderjaw cools to black stone."),
    CHAINWARDEN("chainwarden", Realm.HOLLOW, 1, "Jailer of the Damned", false, 1450, 13, 0.22, 2.2f, 5.4f, BossEvent.BossBarColor.RED, "aurelia:hollow_shade",
            new Lieutenant.Ability[] {Lieutenant.Ability.PULL, Lieutenant.Ability.SLAM, Lieutenant.Ability.SUMMON},
            "Chains rattle in the dark, and go taut.",
            "The Chainwarden falls, and its chains let go."),
    ASHEN_CHOIR("ashen_choir", Realm.HOLLOW, 2, "Three Who Sing Ash", true, 1050, 13, 0.26, 2.6f, 2.6f, BossEvent.BossBarColor.RED, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.SKULLS, Lieutenant.Ability.ZONE, Lieutenant.Ability.BLINK},
            "Three voices begin to sing.",
            "The Choir falls silent, one voice at a time."),
    REEF_CRUSHER("reef_crusher", Realm.DROWNED, 0, "Shell of the Deep", false, 1250, 14, 0.24, 3.8f, 2.4f, BossEvent.BossBarColor.BLUE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.CHARGE, Lieutenant.Ability.BULWARK},
            "The reef rises on eight legs.",
            "The Reef Crusher's shell splits open."),
    DROWNED_ADMIRAL("drowned_admiral", Realm.DROWNED, 1, "Captain of the Sunken Fleet", false, 1550, 14, 0.26, 1.6f, 4.4f, BossEvent.BossBarColor.BLUE, "minecraft:drowned",
            new Lieutenant.Ability[] {Lieutenant.Ability.LEAP, Lieutenant.Ability.PULL, Lieutenant.Ability.SUMMON},
            "A ship's bell rings under the water.",
            "The Admiral goes down with his ship."),
    ABYSSAL_SIREN("abyssal_siren", Realm.DROWNED, 2, "Voice of the Trench", true, 1100, 14, 0.3, 1.6f, 4.0f, BossEvent.BossBarColor.BLUE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.VOLLEY, Lieutenant.Ability.NOVA, Lieutenant.Ability.ROOT},
            "Somewhere, a woman begins to sing.",
            "The Siren's song breaks off."),
    FROSTMAW("frostmaw", Realm.PALE, 0, "the Starving Yeti", false, 1650, 15, 0.28, 2.6f, 4.8f, BossEvent.BossBarColor.WHITE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.LEAP, Lieutenant.Ability.ROOT},
            "Something hungry climbs out of the snow.",
            "Frostmaw collapses into the drifts."),
    RIME_KNIGHT("rime_knight", Realm.PALE, 1, "Sworn to the Silence", false, 1650, 15, 0.3, 1.4f, 4.0f, BossEvent.BossBarColor.WHITE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.BLINK, Lieutenant.Ability.CHARGE, Lieutenant.Ability.NOVA},
            "A knight in black ice draws its sword without a sound.",
            "The Knight shatters."),
    THE_MOURNER("the_mourner", Realm.PALE, 2, "She Who Weeps Snow", true, 1200, 15, 0.28, 1.6f, 4.2f, BossEvent.BossBarColor.WHITE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.VOLLEY, Lieutenant.Ability.NOVA, Lieutenant.Ability.PULL},
            "Someone is weeping in the wind.",
            "The Mourner's veil falls empty to the snow."),
    DUNE_TYRANT("dune_tyrant", Realm.SCARLET, 0, "King of Stings", false, 1550, 17, 0.32, 3.8f, 2.3f, BossEvent.BossBarColor.RED, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.CHARGE, Lieutenant.Ability.VOLLEY, Lieutenant.Ability.LEAP},
            "The dunes split, and a tail rises.",
            "The Tyrant's tail falls limp."),
    SAND_PHARAOH("sand_pharaoh", Realm.SCARLET, 1, "Who Was Buried Waiting", false, 2000, 17, 0.24, 1.6f, 4.6f, BossEvent.BossBarColor.RED, "minecraft:husk",
            new Lieutenant.Ability[] {Lieutenant.Ability.SUMMON, Lieutenant.Ability.ZONE, Lieutenant.Ability.BLINK},
            "An hourglass turns over in the dark.",
            "The Pharaoh's sand runs out."),
    GLASS_DJINN("glass_djinn", Realm.SCARLET, 2, "Furnace of the Sands", true, 1450, 17, 0.3, 2.0f, 4.2f, BossEvent.BossBarColor.RED, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.FIREBALLS, Lieutenant.Ability.NOVA, Lieutenant.Ability.BLINK},
            "The air above the sand begins to burn.",
            "The Djinn cools, cracks and falls in shards."),
    PENDULUM_BUTCHER("pendulum_butcher", Realm.CLOCKWORK, 0, "It Keeps Perfect Time", false, 2100, 18, 0.22, 2.4f, 5.6f, BossEvent.BossBarColor.YELLOW, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.CHARGE, Lieutenant.Ability.BULWARK},
            "A great pendulum begins to swing.",
            "The Butcher winds down and stops."),
    GEARWYRM("gearwyrm", Realm.CLOCKWORK, 1, "Engine Without End", false, 1700, 18, 0.34, 3.0f, 1.9f, BossEvent.BossBarColor.YELLOW, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.CHARGE, Lieutenant.Ability.BOLT, Lieutenant.Ability.LEAP},
            "Gears grind together somewhere below you.",
            "The Gearwyrm seizes up, segment by segment."),
    HOURLESS_ORACLE("hourless_oracle", Realm.CLOCKWORK, 2, "Who Saw Your Death", true, 1500, 18, 0.28, 2.2f, 3.2f, BossEvent.BossBarColor.YELLOW, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.BLINK, Lieutenant.Ability.ROOT, Lieutenant.Ability.VOLLEY},
            "Every clock around you stops.",
            "The Oracle's hands spin free."),
    ROT_BEHEMOTH("rot_behemoth", Realm.MYCELIAL, 0, "Mountain of Spores", false, 1900, 20, 0.22, 4.0f, 3.6f, BossEvent.BossBarColor.PINK, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.ZONE, Lieutenant.Ability.CHARGE},
            "A hill of mushrooms gets up.",
            "The Behemoth sinks back into the rot."),
    PALE_GARDENER("pale_gardener", Realm.MYCELIAL, 1, "Who Tends the Dead", false, 2300, 20, 0.3, 1.6f, 5.8f, BossEvent.BossBarColor.PINK, "aurelia:sporecap",
            new Lieutenant.Ability[] {Lieutenant.Ability.CHARGE, Lieutenant.Ability.SUMMON, Lieutenant.Ability.ROOT},
            "Something tall stoops out of the fungus.",
            "The Gardener withers where it stands."),
    LUMEN_HORROR("lumen_horror", Realm.MYCELIAL, 2, "Light in the Deep", true, 1700, 20, 0.24, 2.8f, 3.8f, BossEvent.BossBarColor.PINK, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.ZONE, Lieutenant.Ability.VOLLEY, Lieutenant.Ability.PULL},
            "A soft light rises out of the dark.",
            "The Lumen Horror's light goes out."),
    HERALD_OF_RUIN("herald_of_ruin", Realm.LAST, 0, "First of the Unmade", false, 3950, 24, 0.24, 2.6f, 6.8f, BossEvent.BossBarColor.PURPLE, "aurelia:husk_guard",
            new Lieutenant.Ability[] {Lieutenant.Ability.SLAM, Lieutenant.Ability.CHARGE, Lieutenant.Ability.NOVA, Lieutenant.Ability.SUMMON},
            "The Herald of Ruin raises its blade.",
            "The Herald of Ruin comes apart."),
    HERALD_OF_SILENCE("herald_of_silence", Realm.LAST, 1, "Last of the Unmade", true, 2900, 24, 0.28, 3.0f, 3.0f, BossEvent.BossBarColor.PURPLE, null,
            new Lieutenant.Ability[] {Lieutenant.Ability.BLINK, Lieutenant.Ability.VOLLEY, Lieutenant.Ability.PULL, Lieutenant.Ability.ROOT},
            "Everything goes quiet.",
            "The Herald of Silence closes its eye.");

    public final String id;
    public final Realm realm;
    /** Which of its realm's lairs it holds: 0, 1 or 2. */
    public final int slot;
    public final String title;
    public final boolean flying;
    public final double health;
    public final double damage;
    public final double speed;
    public final float width;
    public final float height;
    private final BossEvent.BossBarColor bar;
    @Nullable
    public final String minion;
    public final Lieutenant.Ability[] abilities;
    public final String awakenLine;
    public final String deathLine;

    LieutenantKind(String id, Realm realm, int slot, String title, boolean flying, double health, double damage, double speed, float width,
                   float height, BossEvent.BossBarColor bar, @Nullable String minion, Lieutenant.Ability[] abilities, String awakenLine,
                   String deathLine) {
        this.id = id;
        this.realm = realm;
        this.slot = slot;
        this.title = title;
        this.flying = flying;
        this.health = health;
        this.damage = damage;
        this.speed = speed;
        this.width = width;
        this.height = height;
        this.bar = bar;
        this.minion = minion;
        this.abilities = abilities;
        this.awakenLine = awakenLine;
        this.deathLine = deathLine;
    }

    public BossEvent.BossBarColor barColor() {
        return this.bar;
    }

    /** The lieutenants of a realm, in lair order. Empty for a realm without any. */
    public static List<LieutenantKind> of(Realm realm) {
        List<LieutenantKind> out = new ArrayList<>();
        for (LieutenantKind k : values()) {
            if (k.realm == realm) {
                out.add(k);
            }
        }
        return out;
    }

    @Nullable
    public static LieutenantKind of(Realm realm, int slot) {
        for (LieutenantKind k : values()) {
            if (k.realm == realm && k.slot == slot) {
                return k;
            }
        }
        return null;
    }

    @Nullable
    public static LieutenantKind byType(EntityType<?> type) {
        for (LieutenantKind k : values()) {
            if (LieutenantEntities.type(k) == type) {
                return k;
            }
        }
        return null;
    }
}
